### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by spaces-discord** [Persian-Caesar/Ticker-Boy#43]
The bot token you entered is incorrect or the bot has its intents off

**Comment by Sobhan-SRZA** [comment]
Check the bot token to see if it is correct and make sure that you have activated the intents on the Discord development site for your bot.
![911A4520-7408-4377-91B2-E24D30C1A2FC](https://user-images.githubusercontent.com/90289153/231110737-d19a9a0e-bfdc-45fb-b0bc-d4da381857ef.jpeg)
